### EMR Resource Variables
variable "emr_cluster_name"{
    default = "ccoe-testing-emr-001"
}

variable "applications" {
  default = ["Spark", "Hadoop", "Sqoop", "Hive", "Ganglia"]
}

variable tagsmap {
  description = "Applicable only for resource deployment using Terragrunt. ARN of the cross account IAM Role to be assumed by Terraform to provision AWS resources. This value will be passed to the assume_role property in the provider.tf file generated by Terragrunt."
}

variable "ReleaseLabel" {
  description = "Must be a valid EMR release version"
  default     = "emr-5.31.0"
  type        = string
}

variable "LogBucket" {
  description = "The path to the Amazon S3 location where logs for this cluster are stored."
  type        = string
  default     = "wu-ccoe-s3-cf"
}

variable "subnet_id" {}

variable "key_name" {}


variable "EmrMasterSecurityGroup" {
  description = "EMR Master Security Group"
  type        = string
  default     = "sg-02bf874beeda3446f"
}

variable "EmrSlaveSecurityGroup" {
  description = "EMR Slave Security Group"
  type        = string
  default     = "sg-02bf874beeda3446f"
}

variable "slave_security_group" {}

variable "master_security_group" {}

variable "EmrServiceSecurityGroup" {
  description = "EMR Service Security Group"
  type        = string
  default     = "sg-041b7765aeccba34e"
}

variable "Instance_profile"{}

variable "EmrMasterInstanceType" {
  description = "Instance type for the EMR master node."
  type        = string
  default     = "m5.8xlarge"
}

variable "InstanceCount" {
  default = "1"
}

variable "masterinstancegroupname" {}

variable "master_ebs_size" {
  type = number
  description = "master instance volume size"
  default = "32"
}

variable "master_instance_ebs_volume_type" {
  type = string
  description ="master instance volume type"
  default = "gp2"
}

variable "master_volume_per_instance" {
  type = number
  description ="number of ebs volume with this configuration to attach to each EC2 instance "
  default = "1"
}

variable "EmrCoreInstanceType" {
  description = "Instance type for the EMR core nodes"
  type        = string
  default     = "m5.8xlarge"
}

variable "EmrCoreNodes" {
  description = "Number of EMR Core Nodes. Minimum 1"
  type        = number
  default     = 8
}

variable "service_role" {
}
/*
variable "KeyId" {
  description = "Encryption Key ARN"
  default     = "arn:aws:kms:us-east-1:552511075407:key/6925b4e0-c8ac-4f02-9d8e-646d31d63a60"
  type        = string
}
*/
variable "minimum_capacity_units" {
  type        = number
  default     = "2"  
}

variable "maximum_capacity_units" {
  type        = number
  default     = "10"
}

variable "maximum_ondemand_capacity_units" {
  type        = number
  default     = "2"
}

variable "maximum_core_capacity_units" {
  type        = number
  default     = "10"
}

variable "master_instance_fleet_name" {
  type        = string
  description = "Name for the master instance fleet"
  default     = "MasterInstanceFleet"
}

variable "master_instance_type" {
  type        = string
  description = "The instance type of the master nodes"
  default     = "m5.8xlarge"
}

variable "master_weighted_capacity" {
  type        = number
  default     = 1
}

variable "master_bid_price" {
  type        = string
  description = <<EOF
  Bid price for each instance in the master instance fleet, expressed in USD. By setting this attribute,
  the instance fleet is being declared as a Spot Instance, and will implicitly create a Spot request.
  Leave this blank to use On-Demand Instances
  EOF
  default     = ""
}

variable "master_bid_price_as_percentage_of_on_demand_price" {
  type        = number
  default     = 100
  description = "Bid price as percentage of on-demand price for master instances"
}

variable "master_instance_on_demand_count" {
  type        = number
  default     = 1
  description = "Number of on-demand instances for the master instance fleet."
}

variable "master_instance_spot_count" {
  type        = number
  default     = 0
  description = "Number of spot instances for the master instance fleet."
}

variable "master_ebs_volumes_count" {
  type        = number
  description = "Number of volumes to attach to the master nodes"
  default     = 1
}

variable "master_ebs_type" {
  type        = string
  description = "Type of volumes to attach to the master nodes. Valid options are gp2, io1, standard and st1"
  default     = "gp2"
}

variable "master_ebs_size" {
  type        = string
  description = "The volume size, in gibibytes (GiB)."
  default     = "100"
}

variable "master_block_duration_minutes" {
  type        = number
  description = "Duration for master spot instances, in minutes"
  default     = 0
}

variable "master_timeout_action" {
  type        = string
  description = "Timeout action for master instances"
  default     = "SWITCH_TO_ON_DEMAND"
}

variable "master_timeout_duration_minutes" {
  type        = number
  description = "Spot provisioning timeout for master instances, in minutes"
  default     = 10
}

variable "core_instance_fleet_name" {
  type        = string
  description = "Name for the core instance fleet"
  default     = "CoreInstanceFleet"
}

variable "core_instance_type" {
  type        = string
  description = "The instance type of the core nodes"
  default     = "m5.8xlarge"
}

variable "core_weighted_capacity" {
  type        = number
  default     = 1
}

variable "core_instance_on_demand_count" {
  type        = number
  default     = 1
  description = "Number of on-demand instances for the core instance fleet."
}

variable "core_instance_spot_count" {
  type        = number
  default     = 0
  description = "Number of spot instances for the master instance fleet."
}

variable "core_bid_price" {
  type        = string
  description = <<EOF
  Bid price for each instance in the core instance fleet, expressed in USD. By setting this attribute,
  the instance fleet is being declared as a Spot Instance, and will implicitly create a Spot request.
  Leave this blank to use On-Demand Instances
  EOF
  default     = ""
}

variable "core_bid_price_as_percentage_of_on_demand_price" {
  type        = number
  default     = 100
  description = "Bid price as percentage of on-demand price for core instances"
}

variable "core_ebs_volumes_count" {
  type        = number
  description = "Number of volumes to attach to the core nodes"
  default     = 1
}

variable "core_ebs_type" {
  type        = string
  description = "Type of volumes to attach to the core nodes. Valid options are gp2, io1, standard and st1"
  default     = "gp2"
}

variable "core_ebs_size" {
  type        = string
  description = "The volume size, in gibibytes (GiB)."
  default     = "500"
}

variable "core_block_duration_minutes" {
  type        = number
  description = "Duration for core spot instances, in minutes"
  default     = 0
}

variable "core_timeout_action" {
  type        = string
  description = "Timeout action for core instances"
  default     = "SWITCH_TO_ON_DEMAND"
}

variable "core_timeout_duration_minutes" {
  type        = number
  description = "Spot provisioning timeout for core instances, in minutes"
  default     = 10
}

variable "task_instance_fleet_name" {
  type        = string
  description = "Name for the core instance fleet"
  default     = "CoreInstanceFleet"
}

variable "task_instance_type" {
  type        = string
  description = "The instance type of the core nodes"
  default     = "m5.8xlarge"
}

variable "task_weighted_capacity" {
  type        = number
  default     = 1
}

variable "task_instance_on_demand_count" {
  type        = number
  default     = 1
  description = "Number of on-demand instances for the core instance fleet."
}

variable "task_instance_spot_count" {
  type        = number
  default     = 0
  description = "Number of spot instances for the master instance fleet."
}

variable "task_bid_price" {
  type        = string
  description = <<EOF
  Bid price for each instance in the core instance fleet, expressed in USD. By setting this attribute,
  the instance fleet is being declared as a Spot Instance, and will implicitly create a Spot request.
  Leave this blank to use On-Demand Instances
  EOF
  default     = ""
}

variable "task_bid_price_as_percentage_of_on_demand_price" {
  type        = number
  default     = 100
  description = "Bid price as percentage of on-demand price for core instances"
}

variable "task_ebs_volumes_count" {
  type        = number
  description = "Number of volumes to attach to the core nodes"
  default     = 1
}

variable "task_ebs_type" {
  type        = string
  description = "Type of volumes to attach to the core nodes. Valid options are gp2, io1, standard and st1"
  default     = "gp2"
}

variable "task_ebs_size" {
  type        = string
  description = "The volume size, in gibibytes (GiB)."
  default     = "500"
}

variable "task_block_duration_minutes" {
  type        = number
  description = "Duration for core spot instances, in minutes"
  default     = 0
}

variable "task_timeout_action" {
  type        = string
  description = "Timeout action for core instances"
  default     = "SWITCH_TO_ON_DEMAND"
}

variable "task_timeout_duration_minutes" {
  type        = number
  description = "Spot provisioning timeout for core instances, in minutes"
  default     = 10
}
